PRAGMA foreign_keys = ON;


DROP TABLE if EXISTS athlete;
DROP TABLE if EXISTS image;
DROP TABLE if EXISTS sport;
DROP TABLE if EXISTS school;


CREATE TABLE athlete (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  athlete_key TEXT NOT NULL,
  name TEXT NOT NULL,
  gender TEXT NOT NULL CHECK (gender IN ('M', 'F')),
  misc TEXT NOT NULL,
  sport_id INTEGER NOT NULL,
  school_id INTEGER NOT NULL,
  FOREIGN KEY (sport_id) REFERENCES sport(id),
  FOREIGN KEY (school_id) REFERENCES school(id)
) STRICT;

CREATE TABLE image (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  url TEXT NOT NULL,
  athlete_id INTEGER NOT NULL,
  FOREIGN KEY (athlete_id) REFERENCES athlete(id)
) STRICT;

CREATE TABLE sport (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE
) STRICT;

CREATE TABLE school (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE
) STRICT;
